#!/usr/bin/env python3

import sys
import time
import datetime
from pathlib import Path
from subprocess import Popen

def alert(minutes, message):

    platform = sys.platform
    print(platform)
    if platform == "linux" or platform == "linux2":
        command = """sleep %s && notify-send \"%s\" """ % (minutes * 60, task)
    elif platform == "darwin":
        command = """sleep %s && osascript -e 'display notification "" with title "%s" sound name "Pop"'""" % (minutes * 60, task)
    elif platform == "win32":
        raise Exception("Not implemented")

    Popen([command], shell=True)

try:
    minutes = int(sys.argv[1])
    task = " ".join(sys.argv[2:])
except ValueError:
    minutes = str(input('How many minutes? '))
    task = " ".join(sys.argv[1:])

alert(minutes, task)

print("I will alert with %s in %s minute(s)" % (task, minutes))

ts = str(datetime.datetime.now())

with open(str(Path.home()) + "/.timeb-log", "a+") as f:
    f.write("%s: %s" % (ts, task) )
